import type { Metadata } from "next";
import { Roboto } from "next/font/google";
import "./globals.scss";
import Header from "@/ui/Header";
import Navbar from "@/ui/Navbar";
import { BurgerMenuContextProvider } from "@/lib/context/BurgerMenuContext";
import { DarkmodeContextProvider } from "@/lib/context/DarkmodeContext";

export const roboto = Roboto({
  subsets: ["latin"],
  weight: ["400", "500", "700"],
});

const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <DarkmodeContextProvider>
        <BurgerMenuContextProvider>
          <Header />
          <Navbar />
          <main className="main">{children}</main>
        </BurgerMenuContextProvider>
      </DarkmodeContextProvider>
    </html>
  );
}
